### PR TITLE
Mitigate #122 - docker compose vs docker-compose

### PR DESCRIPTION
**Pull request by rainyskye**
Fix for #122 ?

Should check if docker-compose exists, if it does, it will use that, otherwise it'll fall back to assuming docker compose works?

It's (a little) janky, but should work, I haven't properly tested it yet, but I am setting up a otobo instance at home atm, so can test it once that's up and running :)

### CODE REVIEW

**Comment by bschmalhofer** [comment]
Hi @rainyskye ,

thanks for your contribution. Falling back to `docker compose` when `docker-compose` does not exist makes sense to me. I'll merge PR.
Another interesting case is when both `docker-compose` and`docker compose` exist. We need to discuss internally which command takes precedence in this case.

**Comment by rainyskye** [comment]
> Another interesting case is when both `docker-compose` and`docker compose` exist. We need to discuss internally which command takes precedence in this case.

I mean imo `docker compose` should take precedence, it seems like that's what is preferred and most documented now with compose v2 and such.

**Comment by bschmalhofer** [comment]
I agree that `docker compose` should have precedence. But this needs to be properly documented. Otherwise the users will be wonderung why their `otobo_web_1` service suddenly shows up as `otobo-web-1`.

**Comment by rainyskye** [comment]
Maybe a required 
```
Changes <changes> - see _____
Do you understand? Y/N
```
When upgrading?

**Comment by bschmalhofer** [comment]
Sounds good. Additionally with a command line option that specifies the compose command, so that it can be used in other scripts. And an option to skip interaction and use the default command without further questions.

**Comment by rainyskye** [comment]
Would it automatically migrate from `otobo_web_1` to `otobo-web-1`? 

I haven't really payed much attention to it as I haven't had to migrate older stuff as of yet.

**Pull request merged**
