### PR TITLE
Cleanup argument parsing, add docker compose warning

### PR DESCRIPTION
**Pull request by rainyskye**
Also includes the --dontwarn flag, in-case you don't want the warning to display (i.e: scripts/automation)

Continued Fixes for #122 and #123

### CODE REVIEW

**Comment by rainyskye** [comment]
Hey @bschmalhofer, Just wondering if you could check this to see if it needs anything changed?

Thanks :)

**Comment by bschmalhofer** [comment]
Hi @rainyskye,

I like you code style improvements. But I'm hesitant to change the behavior of the script. Could you therefore comment out the '--dontwarn' flag in the help message and the actual calling of docker_warning()? 

An ideal solution would be a reliable detection whether an upgrade to Docker Compose V2 actually happens. But I have no idea how this could be achieved. One uncertainty is that there is even no guarantee that die Containers are running when the script is called. 

We are having an onsite-Meeting at Rother OSS next week. I will also raise the issue there.

Best regards, and thanks for your contribution,
   Bernhard

**Comment by rainyskye** [comment]
Hey @bschmalhofer,

I understand that yeah, I've made the change and had a quick test and all seems good without the docker_warning calls, I also commented out the function and that just to ensure nothing is funky.

Thanks :)

**Review by bschmalhofer — APPROVED** [review]
Thanks!

**Pull request merged**
